# Generated by Django 5.2 on 2025-05-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersbyevent',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
