# Generated by Django 5.2 on 2025-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_isvisible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
