# Generated by Django 5.2 on 2025-05-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_person_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
