# Generated by Django 5.2 on 2025-05-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_event_workersbyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isVisible',
            field=models.BooleanField(default=True),
        ),
    ]
