# Generated by Django 5.2 on 2025-05-19 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('isVisible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚÑáéíóúñ\\s]+$')])),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚÑáéíóúñ\\s]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚÑáéíóúñ\\s]+$')])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='El nombre solo puede contener letras y espacios.', regex='^[A-Za-zÁÉÍÓÚÑáéíóúñ\\s]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('isVisible', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='people_module.person')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_module.place')),
                ('typeEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_module.typeevent')),
            ],
        ),
        migrations.CreateModel(
            name='WorkersByEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_module.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='people_module.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_module.role')),
            ],
        ),
    ]
