# Generated by Django 5.2 on 2025-05-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='typeEvent',
        ),
        migrations.RemoveField(
            model_name='workersbyevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='workersbyevent',
            name='person',
        ),
        migrations.RemoveField(
            model_name='workersbyevent',
            name='role',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='TypeEvent',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='WorkersByEvent',
        ),
    ]
